### PR TITLE
added requirements.txt with required dependencies.

### LINKED ISSUE #18: missing requirements.txt

### PR DESCRIPTION
**Pull request by vishwas78**
Fixes #18

### CODE REVIEW

**Comment by vicente-gonzalez-ruiz** [comment]
Hi @vishwas78, this PR has some sort of conflict (maybe, as a consequence of having accepted the first PR ... I don't know). The other PR has also a conflict. Please, solve them, and again, thank you!

**Comment by vishwas78** [comment]
yeah sure :)

**Comment by vishwas78** [comment]
@vicente-gonzalez-ruiz I have resolved the conflicts and also added newer version of the required packages

**Comment by vicente-gonzalez-ruiz** [comment]
Right now. Thank you, @vishwas78.

**Pull request merged**
