### PR TITLE
changes to strepds files 

### PR DESCRIPTION
**Pull request by sachinsngh165**
cis set of rules as per new DBS set of rules and internet socket implementation instead of unix socket.

### CODE REVIEW

**Comment by cristobalmedinalopez** [comment]
Hi @sachinsngh165 
I see something strange in the overlay of the team. There are several nodes repeated. I presume that there is a problem with the format because some of them are shown like `127.0.0.1,39139` an others like `('127.0.0.1', 39139)`

It is difficult to identify who are malicious, in the console it is shown:
```2018-06-12 12:18:11,549 - __main__ - INFO - List of Malicious
2018-06-12 12:18:11,550 - __main__ - INFO - ['MP1', 'MP2']```
And in the network overlay using the IP, but I don't know what is the IP for the malicious. I used to color it in red.

**Comment by sachinsngh165** [comment]
@cristobalmedinalopez  I was thinking how will splitter distinguish b/w normal peer, monitor peer and malicious peer as we are no longer using unix socket which was using names to distinguish b/w them? Do we need to create a separate mechanism for it ?

**Comment by cristobalmedinalopez** [comment]
@sachinsngh165 oh yes! We have to create a mechanism fot it. Maybe something as simple as telling to the splitter who type of peer you are. It would be used only for simulation purposes, it is unknown in a real scenario.

**Comment by sachinsngh165** [comment]
@cristobalmedinalopez  It would be good if splitter write monitor or malicious peer endpoint to drawing file with their corresponding type so that  we can map their endpoint with type of peer while plotting. Since we need type of peer while drawing network.

**Comment by cristobalmedinalopez** [comment]
@sachinsngh165 Yes, it is a good idea. And of course, the Splitter have to know it first.

**Comment by sachinsngh165** [comment]
You are right Splitter have to know it first, for that i have made a mechanism.

**Comment by sachinsngh165** [comment]
@cristobalmedinalopez  Hey! I made few changes please have a look.

**Comment by cristobalmedinalopez** [comment]
Hi @sachinsngh165 Good Job!
Only a little detail, we are mixing the format used in the chunks, probably due to the change of the communication way between peers. Since we are using struct.pack is not longer necessary to use `b'C'` for the content of the chunk, `'C'` is easier, simpler and it should work.

**Pull request merged**
