### PR TITLE
AF_UNIX socket replaced with AF_INET socket for DBS2 set of rules

### PR DESCRIPTION
**Pull request by sachinsngh165**
I've tested this on my level, everything seems to work fine. But there is one problem regarding permissions. Whenever I restart my computer and run the program for first time it ask me for socket permissions. In this lapse of time while i'm giving it permissions, lots of packet get lost. But if you run the simulation again it won't ask for permissions hence no lost of packets. 
Is anyone facing same the issue ?

### CODE REVIEW

**Comment by cristobalmedinalopez** [comment]
Hi @sachinsngh165 
I've just tested it and it worked fine for me. No problem at all :-)
Thanks!

**Comment by cristobalmedinalopez** [comment]
Merged!
We will have to improve the visualization, but it is a different task.

**Comment by vicente-gonzalez-ruiz** [comment]
Thank you, @sachinsngh165 and @cristobalmedinalopez. Well done!

However, I have a question (that could be addressed in a new issue). Now, the peers are identified by their end-points (which is right). However, this is too much information to be show when the buffers are "printed" (in the UNIX sockets implementation only a number was shown, now the complete end-point is shown).  Do you think that we could use a dictionary indexed by the end-poin to show an ASCII code (for example)? Do you have a different idea?

Thank you!

**Comment by cristobalmedinalopez** [comment]
You are right @vicente-gonzalez-ruiz. We should address it in a new issue.

**Comment by sachinsngh165** [comment]
Yes, We were thinking the same, it is difficult to analyse with so much details.

**Pull request merged**
